"""Build an offline gallery of actual localized PNGs and bound QA."""
import json, shutil
from pathlib import Path
from recover_visual_specs import OUT,ROOT

def main():
    cases=json.loads((OUT/'source_cases.json').read_text())
    locales={p.stem:json.loads(p.read_text()) for p in (OUT/'locales').glob('*.json') if not p.name.endswith('.raw.json')}
    (OUT/'originals').mkdir(exist_ok=True)
    for c in cases:
        if c.get('original_image'):
            src=ROOT/c['original_image'];dst=OUT/'originals'/(c['id']+src.suffix);shutil.copy2(src,dst);c['preview_original']=str(dst.relative_to(OUT))
    records=[json.loads(l) for l in (OUT/'benchmark.jsonl').read_text().splitlines()]
    data=json.dumps({'cases':cases,'locales':locales,'records':records,'validation':json.loads((OUT/'validation.json').read_text())},ensure_ascii=False).replace('</','<\/')
    html='''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>MVisQA · 多语言图像构造</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f4f0;color:#23352e;font:16px system-ui}header{padding:32px 4vw;background:#173d32;color:white}h1{margin:0 0 10px;font-size:30px}header p{max-width:1050px;line-height:1.65;color:#d9e9df}.controls{position:sticky;top:0;background:#fffef9;z-index:2;padding:16px 4vw;display:flex;gap:22px;align-items:center;flex-wrap:wrap;border-bottom:1px solid #d5dfd6}select{font:inherit;padding:8px;border:1px solid #9faea2;border-radius:6px}main{padding:24px 4vw}.case{background:#fff;border:1px solid #d5dfd6;border-radius:12px;padding:24px;margin:0 0 28px}.meta{font-size:13px;color:#67796e}.qa{padding:18px;background:#edf5ed;border-radius:8px;line-height:1.75;margin:18px 0}.gallery{display:grid;grid-template-columns:1fr 1fr;gap:20px}.panel{min-width:0}.panel img{display:block;width:100%;height:auto;border:1px solid #eee}.panel h3{font-size:15px}.note{color:#8c6223;font-size:14px;line-height:1.65}details{margin-top:16px}details img{max-width:100%}a{color:#237152}header a{color:#c9eddb}code{overflow-wrap:anywhere;font-size:12px}@media(max-width:800px){.gallery{grid-template-columns:1fr}.case{padding:14px}}
</style><header><h1>MVisQA / 多语言图像构造试验</h1><p>5 个原始案例 · 3 张 Chart + 2 张 Table · 11 种图像语言 · 55 张真实 PNG · 155 种同语 / 中英跨语 QA 配置。英文作为重绘基线，其他 10 种语言通过统一标签字典绑定图中文字与问题。</p><p>折线图和双轴图由像素恢复，属于近似重建；热图数值来自原图注释，表格来自原始单元格。当前为待人工语义与重建审核的 benchmark 候选，图像中不添加答案或审核提示。</p><a href="README.md">构造与审核说明</a> · <a href="benchmark.jsonl">QA 数据</a> · <a href="validation.json">校验结果</a></header><div class="controls"><label>图像语言 <select id="lang"></select></label><label>QA 语言 <select id="qa"><option value="same">跟随图像</option><option value="zh">中文</option><option value="en">English</option></select></label><label>案例 <select id="case"><option value="all">全部 5 条</option></select></label><span id="stats"></span></div><main id="main"></main><script>const D=__DATA__;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const langs=['zh','en','ja','ko','fr','de','es','pt','ru','ar','hi'];const l=document.querySelector('#lang'),q=document.querySelector('#qa'),cs=document.querySelector('#case');
l.innerHTML=langs.map(k=>`<option value="${k}">${esc(D.locales[k].label)} (${k})</option>`).join('');cs.innerHTML+=D.cases.map((c,i)=>`<option value="${c.id}">${i+1}. ${esc(c.source)}</option>`).join('');
function draw(){const lang=l.value,ql=q.value==='same'?lang:q.value;document.querySelector('#stats').textContent='55 / 55 图像已生成';document.querySelector('#main').innerHTML=D.cases.filter(c=>cs.value==='all'||cs.value===c.id).map((c,i)=>{const r=D.records.find(r=>r.id===c.id&&r.visual_language===lang&&r.query_language===ql);const chart=!c.table?.rows?.length;return `<article class="case" id="case-${D.cases.indexOf(c)+1}"><div class="meta">${esc(c.source)} · ${esc(c.task_tags.join(' / '))}</div><h2>Case ${D.cases.indexOf(c)+1} · ${chart?'Chart':'Table'}</h2><code>${esc(c.base_id)}</code><div class="qa" dir="${ql==='ar'?'rtl':'ltr'}"><strong>Q：</strong>${esc(r.question)}<br><strong>A：</strong>${esc(r.answer)}</div><div class="gallery"><div class="panel"><h3>英文重绘基线</h3><a href="images/en/${c.id}.png" target="_blank"><img src="images/en/${c.id}.png" alt="English reconstruction ${c.id}"></a></div><div class="panel"><h3>${esc(D.locales[lang].label)} · 最终渲染</h3><a href="${r.image}" target="_blank"><img src="${r.image}" alt="${lang} rendered ${c.id}"></a></div></div><p class="note">${chart?'重建审核：像素曲线 / 坐标估计须人工复核，热图保留原图标注数值。':'单元格翻译：保留原始数值与合并单元格结构，原始字符另存于 specs.json / source_cases.json。'}</p><details><summary>查看原始输入与溯源</summary>${c.preview_original?`<img src="${c.preview_original}" alt="Original source">`:`<pre>${esc(c.table.original_raw)}</pre>`}<pre>${esc(JSON.stringify(c.provenance,null,2))}</pre></details></article>`}).join('')}
[l,q,cs].forEach(e=>e.addEventListener('change',draw));draw();</script></html>'''.replace('__DATA__',data)
    (OUT/'index.html').write_text(html)
    print(OUT/'index.html')
if __name__=='__main__':main()
