'use strict';
const $=id=>document.getElementById(id);
let summary,detail,current,visual='en',dirty=false,loadSequence=0;
const text=(id,value)=>{$(id).textContent=typeof value==='string'?value:JSON.stringify(value,null,2)};
async function api(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.error||response.statusText);return data}
function fail(e){text('error',e.message)}
function allowMove(){return !dirty||confirm('当前审核尚未保存，是否放弃修改？')}
function metrics(){const values=[['基础样例',summary.cases.length],['语言',summary.languages.length],['图片 / 应有',`${summary.images} / ${summary.expected_images}`],['QA / 应有',`${summary.qa} / ${summary.expected_qa}`],['完整性问题',summary.issues],['已人工审核',summary.reviewed]];$('metrics').replaceChildren(...values.map(([label,value])=>{const el=document.createElement('div');el.className='metric';el.append(document.createTextNode(label));const n=document.createElement('strong');n.textContent=value;el.append(n);return el}))}
function list(){const term=$('search').value.toLowerCase(),filter=$('filter').value;$('caseList').replaceChildren(...summary.cases.filter(c=>(c.id+' '+c.source).toLowerCase().includes(term)&&(filter==='all'||filter==='incomplete'&&c.issues||filter==='flagged'&&c.flagged||filter==='todo'&&c.reviewed<c.count)).map(c=>{const b=document.createElement('button');b.className='case'+(detail?.id===c.id?' active':'');const title=document.createElement('strong');title.textContent=c.source+' · '+c.kind;const id=document.createElement('span');id.textContent=c.id;const state=document.createElement('small');state.textContent=`人工 ${c.reviewed}/${c.count} · 自动待审 ${c.flagged} · 完整性异常 ${c.issues}`;b.append(title,id,state);b.onclick=()=>openCase(c.id).catch(fail);return b}))}
async function openCase(id,target){if(!allowMove())return;const sequence=++loadSequence;const loaded=await api('/api/case/'+encodeURIComponent(id));if(sequence!==loadSequence)return;detail=loaded;dirty=false;$('empty').hidden=true;$('detail').hidden=false;text('caseTitle',summary.cases.find(c=>c.id===id).source+' / '+id);if(target)visual=target.image_language;renderLanguages();setQueryOptions(target?.query_language);list()}
function renderLanguages(){$('languages').replaceChildren(...summary.languages.map(lang=>{const rows=detail.rows.filter(r=>r.image_language===lang);const done=rows.filter(r=>r.manual_review.verdict&&r.manual_review.verdict!=='unreviewed'&&!r.manual_review.stale).length;const b=document.createElement('button');b.textContent=lang+' '+done+'/'+rows.length;b.className=(visual===lang?'active ':'')+(!rows.length?'missing':'');b.onclick=()=>{if(!allowMove())return;visual=lang;dirty=false;renderLanguages();setQueryOptions()};return b}))}
function setQueryOptions(preferred){const languages=[...new Set(detail.rows.filter(r=>r.image_language===visual).map(r=>r.query_language))];$('queryLang').replaceChildren(...languages.map(l=>new Option(l,l)));$('queryLang').value=languages.includes(preferred)?preferred:(languages.includes(visual)?visual:languages[0]||'');renderRow()}
function showImage(id,url){const box=$(id);box.replaceChildren();if(!url){box.textContent='该图像不可用';return}const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';const img=document.createElement('img');img.src=url;img.alt=id==='original'?'上游原图':visual+' 本地化图表';img.onerror=()=>{box.textContent='图片不存在或无法读取'};a.append(img);box.append(a)}
function renderRow(){current=detail.rows.find(r=>r.image_language===visual&&r.query_language===$('queryLang').value);text('coverage',detail.issues.join('\n'));text('saved','');if(!current){text('coverage','该语言缺少 QA 配置。\n'+detail.issues.join('\n'));$('save').disabled=true;for(const id of ['sourceQ','sourceA','query','answer','audit'])text(id,'');showImage('localized',null);showImage('original',detail.original);return}$('save').disabled=false;text('position',current.configuration+' · '+current.image_language+' → '+current.query_language);showImage('original',detail.original);showImage('localized','/asset/'+current.id);text('localizedTitle','图表语言：'+visual);text('sourceQ',current.original_query);text('sourceA',current.original_answer);text('query',current.query);text('answer',current.answer);text('audit',current.audit);const a=detail.locales.en?.labels||{},b=detail.locales[visual]?.labels||{},c=detail.locales[current.query_language]?.labels||{};$('labels').replaceChildren(...[...new Set([...Object.keys(a),...Object.keys(b),...Object.keys(c)])].map(key=>{const tr=document.createElement('tr');for(const value of [key,a[key],b[key],c[key]]){const td=document.createElement('td');td.dir='auto';td.textContent=value===undefined?'[missing]':value;tr.append(td)}return tr}));const review=current.manual_review;$('verdict').value=review.verdict||'unreviewed';$('notes').value=review.notes||'';$('reviewer').value=review.reviewer||localStorage.getItem('mstructqa-reviewer')||'';if(review.stale)text('saved','旧审核对应的数据已变化，请重新确认');else if(review.updated_at)text('saved','已保存：'+review.updated_at);dirty=false}
$('search').oninput=list;$('filter').onchange=list;
$('queryLang').onchange=()=>{if(!allowMove()){$('queryLang').value=current.query_language;return}renderRow()};
for(const id of ['verdict','notes','reviewer'])$(id).oninput=()=>{dirty=true;text('saved','尚未保存')};
$('save').onclick=async()=>{if(!current)return;const row=current;$('save').disabled=true;try{const review=await api('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,fingerprint:row.fingerprint,verdict:$('verdict').value,notes:$('notes').value,reviewer:$('reviewer').value})});row.manual_review=review;localStorage.setItem('mstructqa-reviewer',review.reviewer);dirty=false;summary=await api('/api/summary');metrics();list();renderLanguages();text('saved','已保存到本地审核文件')}catch(e){fail(e)}finally{$('save').disabled=false}};
$('next').onclick=async()=>{try{if(!allowMove())return;dirty=false;const index=current?detail.rows.indexOf(current):-1;const ordered=[...detail.rows.slice(index+1),...detail.rows.slice(0,index)];const target=ordered.find(r=>!r.manual_review.verdict||r.manual_review.verdict==='unreviewed'||r.manual_review.stale);if(target){visual=target.image_language;renderLanguages();setQueryOptions(target.query_language);return}const ci=summary.cases.findIndex(c=>c.id===detail.id);const others=[...summary.cases.slice(ci+1),...summary.cases.slice(0,ci)];const next=others.find(c=>c.reviewed<c.count);if(next)await openCase(next.id);else text('saved','没有其他未审核配置')}catch(e){fail(e)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
(async()=>{summary=await api('/api/summary');metrics();list();if(summary.cases.length)await openCase(summary.cases[0].id)})().catch(fail);
